services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    command: npm run start
    volumes:
      - ./backend/src:/app/src
      - ./backend/public:/app/public
    env_file: ./backend/.env
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    env_file: ./frontend/.env
